# Generated by Django 6.0 on 2026-04-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='release_date',
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='short_description',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
