# Generated by Django 6.0.2 on 2026-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='crew',
            field=models.TextField(default='Unknown crew', help_text='Comma separated crew names'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
